# Theme configuration for hexo-theme-modern

# Menu - navigation links
menu:
  home: /
  archives: /archives
  about: /about

# Avatar
avatar: /img/avatar.png

# Favicon
favicon: /img/favicon.png

# CDN for external libraries if needed
cdn:
  # Noto Serif SC font
  google_fonts: 'https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@500&display=swap'
